// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHxd3FIVrx_5553ZE8-DIZ9vjr4w94RQ',
    appId: '1:945114108745:web:8b887d5ae7bd2e2dda4098',
    messagingSenderId: '945114108745',
    projectId: 'instagram-clone-80605',
    authDomain: 'instagram-clone-80605.firebaseapp.com',
    storageBucket: 'instagram-clone-80605.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Tjxe5nB6EkFjQo38VVardIBZGQg_ym4',
    appId: '1:945114108745:android:ef855c622adc54c2da4098',
    messagingSenderId: '945114108745',
    projectId: 'instagram-clone-80605',
    storageBucket: 'instagram-clone-80605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPeSxzYUbYJnBriYwERT2N9064RdMv-VA',
    appId: '1:945114108745:ios:bca4690edaa94eb5da4098',
    messagingSenderId: '945114108745',
    projectId: 'instagram-clone-80605',
    storageBucket: 'instagram-clone-80605.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPeSxzYUbYJnBriYwERT2N9064RdMv-VA',
    appId: '1:945114108745:ios:bca4690edaa94eb5da4098',
    messagingSenderId: '945114108745',
    projectId: 'instagram-clone-80605',
    storageBucket: 'instagram-clone-80605.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXHxd3FIVrx_5553ZE8-DIZ9vjr4w94RQ',
    appId: '1:945114108745:web:4cedd4e007c1772fda4098',
    messagingSenderId: '945114108745',
    projectId: 'instagram-clone-80605',
    authDomain: 'instagram-clone-80605.firebaseapp.com',
    storageBucket: 'instagram-clone-80605.firebasestorage.app',
  );
}
